version: '3'
services:

  nextjs:
    build: ./
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: postgres
      SESSION_SECRET: 523ea32asfd#@324ewfdsA
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DOMAIN: https://www.ex4123432432ample.com
      APP_PORT: 3000

    depends_on:
      - postgres
      - redis

  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - nextjs
      - postgres
      - redis

  postgres:
    container_name: 'postgres'
    image: 'postgres'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - './init.sql:/docker-entrypoint-initdb.d/init.sql'

  redis:
    container_name: 'redis'
    image: 'redis'
    ports:
      - 6379:6379